import HotCategoryGrid from "@/components/layouts/hot-category-grid";
import MainNav from "@/components/layouts/main-nav";
import Image from "next/image";

export default function Home() {
  const forSell = [
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
    {
      city: "Астана",
      rating: "9.5",
      isChecked: true,
      roomNumber: "5 комнатная квартира",
      floor: "4",
      floorFrom: "9",
      areaSq: "150",
      price: "12000000",
      images: [
        "/random/1.jpg",
        "/random/2.jpg",
        "/random/3.jpg",
        "/random/4.jpg",
        "/random/5.jpg",
        "/random/6.jpg",
      ],
    },
  ];

  return (
    <main className="flex min-h-screen bg-slate-100 flex-col px-24">
      <HotCategoryGrid title="Продажа" data={forSell} />
      <HotCategoryGrid title="Аренда" data={forSell} />
    </main>
  );
}
