import { Annoncement } from "@/app/cabinet/annoncements/page";

export const annoncements: Annoncement[] = [
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sadfsdf454sdfsdf",
    categoryType: "квартира",
    serviceType: "продажа",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Актау, 17 мкр., 7/57",
    rating: "9.0",
    isChecked: true,
    roomNumber: "3",
    floor: "2",
    floorFrom: "5",
    areaSq: "1200",
    price: "250000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 0,
      hurryModifier: 0,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "active",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "1",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "archived",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "oioioidsfsd5-7sdfsdf",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "PREMIUM",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
  {
    city: "Астана, Есильский р-он, ул. Сарайшык, 15",
    rating: "9.8",
    isChecked: true,
    roomNumber: "5",
    floor: "12",
    floorFrom: "18",
    areaSq: "130",
    price: "35000000",
    images: [
      "/random/1.jpg",
      "/random/2.jpg",
      "/random/3.jpg",
      "/random/4.jpg",
      "/random/5.jpg",
      "/random/6.jpg",
    ],
    phase: "moderation",
    phone: "87777586999",
    createdAt: new Date("2024-02-01"),
    id: "sdfjkjkljl-4558sdf",
    categoryType: "квартира",
    serviceType: "аренда",
    serviceTypeExt: "посуточно",
    subscription: new Date("2024-03-15"),
    modificators: {
      topModifier: 1,
      hotModifier: 5,
      hurryModifier: 1,
    },
    companySubscription: "TURBO",
    stats: {
      allCount: 100,
      allMobileCount: 80,
      lastSevenCount: 20,
      lastSevenCountMobile: 15,
      todayCount: 5,
      todayCountMobile: 3,
      graphicData: [
        { name: "Пон", uv: 400, pv: 2400 },
        { name: "Вт", uv: 300, pv: 1398 },
        { name: "Ср", uv: 200, pv: 9800 },
        { name: "Чет", uv: 278, pv: 3908 },
        { name: "Пят", uv: 189, pv: 4800 },
        { name: "Суб", uv: 239, pv: 3800 },
        { name: "Вос", uv: 349, pv: 4300 },
      ],
    },
  },
];
